language: node_js
node_js:
- 8
- 10
before_install:
- npm install -g npm
script:
- npm install
- npm run pretest
deploy:
  provider: heroku
  api_key:
    secure: RTX23iBR3MWwRAxx7WBSA0gLnQn/zoMxHwbca0mT2qnvZS5uUM7OyAOVw4zrmhN7WHd56bNjf07YoYaLhDXss18+YSnFcpyX8prkcM8YpUT5naSinXBvIM0LTZxqbZvfzHBKfjYYHaJvkYVjpIq0kAfl2n7IfTn8Dx7deHPTNRjesq3NMk6vh/cjgpTnSMphTTXsRvLOgBAycZ8A0Ajdj36QYWbKSdb+WAvv/uDNr3rdmAdCyU5jSPiPXedD8LF+YR4bUIqhx/glPoPKXYzwTYdNixxmL+X6FYPrnb7Xcj7GTCZpQwjVzijWPvhpfHJb4bi9SnIvtURM8Gs+iYPTyCGxNUeuWI0WxpAhDQPYHDBvTydMrQY7nSUDDPMMxLjW/QbbvOBeg2exngFZh4t1B3nQhG3Hzu8wmaOmf1va3VKBAFEdKlYqyKveelwMGe6M5h40IB+Gvl175to6uLpH6lWOWGEdy/ImJQo9qHwDlmuN3mL0medyXT6xJE7lBmOOcR4s3Zwsjldipsg9Ki9EK5IlcNL4Wtctb/qNsWm9SEY82qPSUiGAavDma3Ce3ex6Cz4nxhLkoJk2NtyQkHyiKbVcEMsLkSZoczR06k23/5y/Tt6/7yw9ZOxoQLntjaxqNxkW5JTiv5m0paXPe00kDNnol9bH0q7WVOhZ1IsSGmE=
  app: corona-watch-server
  on:
    repo: geepalik/coronawatch_server
