language: node_js
node_js:
  - 8
  - 10
before_install:
  - npm install -g npm
script:
  - npm install
  - npm run pretest
deploy:
  provider: heroku
  api_key:
    secure: oEPSpinuT4ft5kYJRIsdz3E3SF1spSW7VIX5hYNpFpVUOtw4Q6CrjBSrNGrhF1kJ5xInU+Jji88aEcpoZQi7WRdagPu9axBjMr5mWN1vGHZ4ce5uAN6knwl9/AW1YmPo4ZGhrWqk
      QgiiYZTMI3/15P1TV22gJPv16fs5q0ua1FqygxbxXxxN6DG3jw0sqm9co8/NIfa59uAnETnWj4Exf7lfdUDJa/3pW77m/VtwMtB6kyz2HoqQ4mb5plJV+zCkcW7wa6Mrm2KRAaNO3LwjZwJCckd
      WaeA8Uyd+bVtEjHWfMNAyrHGCqje49R8A5vTKNhZIve8IRUAKdJO2EuUBatN+HQdEKqkDtyzcLskKM35LJ8wC23jnY49V2HGh6dJmYsniEilM+XUrdrUUDb+uDVqzdLZl8jX0qsy3uwmEd18i8h
      MyM5KEa8A5wl35WWUP1gMaGcOdbmgHwXNq9r5Pnz2TETgxc7p+L9JXUFAHzoul8cNvIr7PEyyGxBsPFxZvAPUHsJD1WWry79fbYGcu5Ot7aTVsKcQnYrkG/kjk1kZvPUUgNgsT69Qsw+JS6Mh6e
      mwTK8lopPxMuw9kj09Eg2qJ4aNHyl6/GOs2RB3pHry0D7s+HcaxOTRZelHrK3jxyGelxMO3y4uaYW0t1fRtfx14h49670XyfQrUlFSS98I=
  app: corona-watch-server
  on:
    repo: geepalik/coronawatch_server