language: node_js
node_js:
- 8
- 10
before_install:
- npm install -g npm
script:
- npm install
- npm run pretest
deploy:
  provider: heroku
  api_key:
    secure: IDMKGKOcNWefUsHY0wstDrp7YgIRGohXZ5QPrVp9DtxhfbGppItoB5NmBBasS7J42EzukuA/ZbZOelJojuyX0RFGdM5tWfQq2o56SJgQ+surxmFwkKuRHkzuXO+LmxZS/m87RqzyhKck3t6wosMOuNMr0ajlSqNrHbK5D/mqk1PFswYsXeYB6yE6onb90LhWCBwjeQ+WYQ/nRhQ+ltFyauLp6tfVI0Xbv+oDSTu7um+2uEKoJkZ/JDjBc3Y1fTQ6Q28Jlm570kLgkt8aJvlpjU52lDnIMpVsiJp57NGsg0dMR0uIJv83ft6VBRTQsNLp7O2eeGin8/BAvUG9b1ST5/ucmzu0/xFaThV+pymIpygXGaYC9wBaFcVyr9Mt28WLQPyqInld2aBuUNCoe5yshW8JLUU2O6N07rgd0kuujgH+ojm0oyBw6ZsALe0dPc+BGhrE9DBUkbEiVe1z5AyGzCzHHfbEOXFKGjvlShAUKNMAv/06BrVzyDvqfYnaxBAA8W+f7jPZbXPoIpKSEtZCpzxc849LxTj9B0jHwzaAkeT2k29TWgAG++o8xwesPi7zrtGlL45W6mIqxUp6xkYj5urnLb+WZdL5c5l+GOCrDaby9oBtMDnLC1XT6zWJCAsGYfxn0LJqtaxJa/i9YB+GEmdhpWTIeKHsTTvu88dRM/o=
  app: corona-watch-server
  on:
    repo: geepalik/coronawatch_server
